#ifndef Pins_Motor_h
#define Pins_Motor_h

#define MOTOR_SELECTION A3

#define MOTOR1_SPEED A0
#define MOTOR2_SPEED A1

#define MOTOR1_START_PIN PIN1
#define MOTOR1_STOP_PIN PIN2
#define MOTOR1_PWM_PIN PIN3
#define MOTOR1_FB_PIN 100

#define MOTOR2_START_PIN PIN4
#define MOTOR2_STOP_PIN PIN5
#define MOTOR2_PWM_PIN PIN6
#define MOTOR2_FB_PIN 101

#define MOTOR1_FAULT A4
#define MOTOR2_FAULT A5

#endif